

version: '3.8'

services:
  backend:
    image: node:22-alpine
    volumes:
      - ./backend:/app
    working_dir: /app
    command: >
      sh -c "npm install
      && npm run start"
    ports:
      - "3001:3001"
    container_name: hello-docker-backend

  frontend:
    image: node:22-alpine
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npx live-server --port=5000 
    ports:
      - "80:5000"
    container_name: hello-docker-frontend
